name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-kg
      - name: check if there are changes
        run: |
         if git diff --exit-code; then
             echo "::set-env name=diff_exitst::false"
         else
             echo "::set-env name=diff_exists::true"
         fi
      - name: Create new branch and push changes if file has been updated
        if: env.diff_exists == 'true'
        run: |
	 git checkout -b chore/update-file
         git push --set-upstream origin chore/update-file
         git add -u
         git commit -m "github actions: updating file"
         git push
          
